config/routes.rb
Rails.application.routes.draw do
  resources :dashboards do
    member do
      patch :move
    end
  end
  devise_for :users
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 2 }

  acts_as_list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  attr_writer :login
  validate :validate_username
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  
  has_many :dashboards, dependent: :destroy

  def index
    @users = User.all
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
        devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
        devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_dashboard, only: [:show, :edit, :update, :destroy, :move]
  before_action :authenticate_user!
  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
    @dashboard = Dashboard.find(params[:id])
  end

  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
  end

  # GET /dashboards/1/edit
  def edit
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(dashboard_params)
    @dashboard.user = current_user
    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard }
      else
        format.html { render :new }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboards/1
  # PATCH/PUT /dashboards/1.json
  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard }
      else
        format.html { render :edit }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard.destroy
    respond_to do |format|
      format.html { redirect_to dashboards_url, notice: 'Dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move
    @dashboard.insert_at(params[:position].to_i)
    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard
      @dashboard = Dashboard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dashboard_params
      params.require(:dashboard).permit(:title, :description, :position)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dashboards/_form.html.erb
<%= form_with(model: dashboard, local: true) do |form| %>
<% if dashboard.errors.any? %>
<div id="error_explanation", style="font-size:20px; color:gray;" >
  <h2><%= pluralize(dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

  <ul>
    <% dashboard.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :title, style:"font-size:20px; font-weight: bold;" %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.label :description, style:"font-size:20px; font-weight: bold;" %>
  <%= form.text_field :description %>
</div>

<div class="actions">
  <%= form.submit :class => 'btn btn-secondary btn-sm' %>
</div>
<% end %>

app/views/dashboards/edit.html.erb
<div style="text-align: center">
    <div style="display: inline-block; text-align: left;" class="card card-body mb-4">
        <h1 style="-webkit-text-stroke-width: 0.5px;
-webkit-text-stroke-color: gray;">Editing Dashboard</h1>

        <%= render 'form', dashboard: @dashboard %>
        <div class="btn-group">
            <%= link_to 'Show', @dashboard, class: "btn btn-info btn-sm" %>
            <%= link_to 'Back', dashboards_path, class: "btn btn-primary btn-sm"%>
        </div>
    </div>
</div>

app/views/dashboards/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1 style="-webkit-text-stroke-width: 0.7px;
    -webkit-text-stroke-color: gray; font-weight:bold">Dashboards</h1>
  </div>
  <div class="col-sm-6 text-right">
    <%= link_to 'New Dashboard', new_dashboard_path, class: 'btn btn-secondary' %>
  </div>
</div>

<div data-controller="sort" data-sort-url="/dashboards/:id/move">
  <% current_user.dashboards.order(position: :asc).each do |dashboard| %>
  <div data-id="<%= dashboard.id %>" class="card card-body mb-4">
    <h2><%= dashboard.title %></h2>
    <%= dashboard.description %>
    <div class="text-right">
      <div class="btn-group">
        <%= button_to 'Show', dashboard_path(dashboard), :method => 'get', :class => "btn btn-info btn-sm", id: dom_id(dashboard) %>
        <%= button_to 'Edit', edit_dashboard_path(dashboard), :method => 'get', :class => "btn btn-secondary btn-sm" %>
        <%= button_to 'Delete', dashboard_path(dashboard),
            method: :delete,
            data: { confirm: 'Are you sure you want to delete the dashboard?' },
            :class => "btn btn-danger btn-sm" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/dashboards/new.html.erb
<div style="text-align: center">
    <div style="display: inline-block; text-align: left;">
        <h1 style="-webkit-text-stroke-width: 0.5px;
-webkit-text-stroke-color: gray;">New Dashboard</h1>

        <%= render 'form', dashboard: @dashboard %>

        <%= link_to 'Back', dashboards_path , class: "btn btn-primary btn-sm"%>
    </div>
</div>

app/views/dashboards/show.html.erb
<div style="text-align: center">
  <div style="display: inline-block; text-align: left;font-weight:bold; font-size:20px; -webkit-text-stroke-width: 0.2px;
  -webkit-text-stroke-color: gray;" class="card card-body mb-4">
    <p>
      <strong>Title:</strong>
      <%= @dashboard.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @dashboard.description %>
    </p>

    <p>
      <strong>Position:</strong>
      <%= @dashboard.position %>
    </p>

    <p>
      <strong>User:</strong>
      <%= @dashboard.user.username %>
    </p>
    <div class="btn-group">
      <%= link_to 'Edit', edit_dashboard_path(@dashboard), class: "btn btn-info btn-sm"  %>
      <%= link_to 'Back', dashboards_path, class: "btn btn-primary btn-sm" %>
    </div>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Home", root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboards_path, class: 'nav-link'%>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <% if current_user %>
            <p class="nav-link"><%=current_user.username%></p>
          <% end %>
        </li>
        <li class="nav-item">
          <% if current_user %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path, class: 'nav-link' %>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DashboardApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style> 
      #tere { 
          width:80%; 
          margin-left: 10%;
          margin-right: 10%;
      } 
  </style>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div id="tere">
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="text-center" style="text-shadow: 1px 1px gray">
    <h1>Home page</h1>

    <% if current_user %>
    <h3>Welcome, <%=current_user.username%>!</h3>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-primary btn-sm"  %>
    <% else %>
    <h3>Please sign in</h3>
    <div class="btn-group">
        <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary btn-sm" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm" %>
    </div>
    <% end %>
</div>